FreeBSD-ports: { url: "https://pkg.FreeBSD.org/${ABI}/latest" }
FreeBSD-base:  { url: "https://pkg.FreeBSD.org/${ABI}/base_release_${VERSION_MINOR}", enabled: yes }
FreeBSD-ports-kmods: { enabled: no }
