FreeBSD-ports: { url: "https://pkg.fastly.FreeBSD.org/${ABI}/latest" }
FreeBSD-base:  { url: "https://pkg.fastly.FreeBSD.org/${ABI}/base_release_${VERSION_MINOR}", enabled: yes }
FreeBSD-ports-kmods: { url: "https://pkg.fastly.FreeBSD.org/${ABI}/kmods_quarterly_${VERSION_MINOR}", enabled: yes }
