global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_fe
    bind *:4000
    default_backend http_be

backend http_be
    http-request return status 200 content-type "text/plain" lf-string %H

